### ISSUE TITLE
Update user guide

### ISSUE THREAD

**Issue by zhaojj2209** [AY2021S1-CS2103T-W16-3/tp#131]
This issue will be used to document all future edits to be made to the user guide.

**Comment by ianyong** [comment]
Define the allowed inputs for `Title` and `Category` more explicitly in the user guide. The intricacies of the input validation cannot be captured within `MESSAGE_CONSTRAINTS` without making it unnecessarily verbose which is not user friendly.

See #130.

**Comment by wltan** [comment]
Proposed improvements based on discussion in CS2101:
- Add general description of what each tab is for and what the user can expect (including screenshot)
- For commands with aliases/general command words, the title can show just the main command and then list below the alias and/or tabs the general command can be used on
- Split transaction -> income and expense for edit and delete commands. This is because the user guide should be based on features available to the user, instead of what commands have been implemented behind the scenes.
- Glossary to tell the user (or potential user/PE tester) what a transaction/income/expense represents in the real world, and what the data fields (title, amount, date category) are for.

**Comment by wltan** [comment]
https://github.com/AY2021S1-CS2103T-W16-3/tp/blob/ed88fc46ac0345a0b6a31681d573b5756bea616a/src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/EditCommandParser.java#L64-L78

An edit command with an argument `c/` has been specially coded to represent an edit to no categories. This fact should be captured in the user guide, otherwise the user may infer incorrectly from the add commands that whatever follows `c/` must be nonempty.

**Comment by wltan** [comment]
UG bug: alias for list commands (`lse`, `lsi`) are not found in the user guide

**Comment by ianyong** [comment]
Remove all abbreviation elements `<abbr>` from the user guide and write out the contents of these tags explicitly.

Not only does this confuse CELC, it also confuses our peers as seen in #243.

**Comment by ianyong** [comment]
Add acknowledgements for all libraries used.

**Comment by ianyong** [comment]
Add badge for license.

**Comment by wltan** [comment]
Inconsistent tense for headings under Section 4. Some **verbs** are in present continuous tense, while others are in simple present tense.

![image](https://user-images.githubusercontent.com/53135010/97786719-843ec180-1be8-11eb-8105-6aa14d4d122d.png)

![image](https://user-images.githubusercontent.com/53135010/97786732-91f44700-1be8-11eb-89a6-b0715c07e578.png)

**Comment by ianyong** [comment]
Add a note somewhere in the user guide that Fine$$e deals with transactions and not items. See https://github.com/AY2021S1-CS2103T-W16-3/tp/issues/238#issuecomment-721108856.
